### ISSUE TITLE
config file missing

### ISSUE THREAD

**Issue by lazyLuizi** [kaist-cvml-lab/part-clipseg#2]
Hi
Thanks for sharing awesome work and open sourcing your project!

However, I don't see any config files referred in your readme. `configs/zero_shot/partclipseg_voc_oracle.yaml`

Could you please double check if readme is correct or missed to upload config files?

**Comment by JihoChoi** [comment]
Thank you for taking an interest in our project and for your kind words about our work!

We appreciate you pointing out the missing config files.
It turns out that we accidentally included them in the `.gitignore` file, which led to their exclusion.
We have now added the missing files, and you can find them at the following location:
`https://github.com/kaist-cvml/part-clipseg/tree/main/configs/zero_shot/`

Thank you again!
