### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by nhw649** [kaist-cvml-lab/part-clipseg#3]
Why does the performance under the Pred-All setting in the initial version of the paper perform well, but the final version shows a significant decline? What changes are made that cause this?
initial version:
![image](https://github.com/user-attachments/assets/c94d7946-600d-4514-a86b-6b4c2581ae32)
final version:
![image](https://github.com/user-attachments/assets/f23c76d5-785f-4dec-8260-2ae4c46e42b9)

**Comment by JihoChoi** [comment]
Thank you for your interest in our research. In Version 1 of our evaluation, we identified certain limitations that were addressed in Version 2 to improve the assessment process.

In Version 1, we employed the conventional mIoU evaluation method, which includes all areas of the dataset, including the background. However, this approach resulted in inaccurate assessments in regions lacking Part GT annotations. For instance, as illustrated in Figure 1, when Part GT labels were provided for only one dog, predictions for other dogs were penalized unfairly, leading to inappropriate penalties. This issue stemmed from the limited Part-level annotations in the OV-PARTS dataset. Consequently, the Version 1 evaluation excluded the background class from performance metrics.

To address this, Version 2 introduced a revised evaluation method. Specifically, regions without GT Part annotations were entirely excluded from the evaluation, enabling a fairer assessment that incorporated performance on the background class. As a result, the final evaluation in Version 2 employed the standard IoU metric, including the background class, for areas with Part GT annotations.

We believe these modifications allow for more accurate measurement of the `Pred-All` setup in OVPS performance. While the overall performance trends remained consistent between Version 1 and Version 2, the absolute performance scores showed a decline due to the methodological adjustments.

Thank you very much.

![figure1](https://github.com/user-attachments/assets/1d1e1ec1-6667-4126-bb85-ba3c5723b82f)

**Comment by nhw649** [comment]
> Thank you for your interest in our research. In Version 1 of our evaluation, we identified certain limitations that were addressed in Version 2 to improve the assessment process.
> 
> In Version 1, we employed the conventional mIoU evaluation method, which includes all areas of the dataset, including the background. However, this approach resulted in inaccurate assessments in regions lacking Part GT annotations. For instance, as illustrated in Figure 1, when Part GT labels were provided for only one dog, predictions for other dogs were penalized unfairly, leading to inappropriate penalties. This issue stemmed from the limited Part-level annotations in the OV-PARTS dataset. Consequently, the Version 1 evaluation excluded the background class from performance metrics.
> 
> To address this, Version 2 introduced a revised evaluation method. Specifically, regions without GT Part annotations were entirely excluded from the evaluation, enabling a fairer assessment that incorporated performance on the background class. As a result, the final evaluation in Version 2 employed the standard IoU metric, including the background class, for areas with Part GT annotations.
> 
> We believe these modifications allow for more accurate measurement of the `Pred-All` setup in OVPS performance. While the overall performance trends remained consistent between Version 1 and Version 2, the absolute performance scores showed a decline due to the methodological adjustments.
> 
> Thank you very much.
> 
> ![figure1](https://private-user-images.githubusercontent.com/5732211/390713877-1d1e1ec1-6667-4126-bb85-ba3c5723b82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTc4MTMsIm5iZiI6MTczMjg1NzUxMywicGF0aCI6Ii81NzMyMjExLzM5MDcxMzg3Ny0xZDFlMWVjMS02NjY3LTQxMjYtYmI4NS1iYTNjNTcyM2I4MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMDUxODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZkNmI4N2JkMGJlNzRmMDY4MzVmN2QyZjE4NmMyZGMxM2QzZWNiNjcyNTljMDVkMGQ0ZDFkNTljNmQzZGFhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ytCuMJCTCeNOGYpdqZiwQNkyGzoT2_GjckqkXEWVQVk)

Thank you for your reply.
